from __future__ import annotations

from pathlib import Path
from typing import Any

from .paths import app_dir, ensure_app_dirs
from .util import pythonw_executable, run_cmd


TASK_NAME = "CodexSyncAutoSync"
LAUNCHER_NAME = "run-sync.pyw"


def _project_root() -> Path:
    return Path(__file__).resolve().parent.parent


def _ensure_launcher() -> Path:
    """生成一个 .pyw 启动器，让定时任务用 pythonw 静默运行 sync-now（无黑框）。"""
    ensure_app_dirs()
    root = _project_root()
    launcher = app_dir() / LAUNCHER_NAME
    content = (
        "# Auto-generated by codex_sync install-task.\n"
        "# Silent periodic sync launcher: run with pythonw.exe so no console window pops up.\n"
        "import os\n"
        "import sys\n"
        "\n"
        f'ROOT = r"{root}"\n'
        "os.chdir(ROOT)\n"
        "if ROOT not in sys.path:\n"
        "    sys.path.insert(0, ROOT)\n"
        "\n"
        "try:\n"
        "    from codex_sync.cli import main\n"
        '    main(["sync-now", "--skip-unchanged-snapshot"])\n'
        "except Exception:\n"
        "    import datetime\n"
        "    import traceback\n"
        '    log = os.path.join(os.path.expanduser("~"), ".codex-sync", "logs", "task-sync-error.log")\n'
        "    os.makedirs(os.path.dirname(log), exist_ok=True)\n"
        '    with open(log, "a", encoding="utf-8") as fh:\n'
        '        fh.write("\\n=== " + datetime.datetime.now().isoformat() + " ===\\n")\n'
        "        traceback.print_exc(file=fh)\n"
    )
    launcher.write_text(content, encoding="utf-8")
    return launcher


def _task_command() -> str:
    launcher = _ensure_launcher()
    return f'"{pythonw_executable()}" "{launcher}"'


def install_windows_task(minutes: int = 3) -> dict[str, Any]:
    minutes = max(1, int(minutes))
    command = _task_command()
    args = [
        "schtasks.exe",
        "/Create",
        "/F",
        "/SC",
        "MINUTE",
        "/MO",
        str(minutes),
        "/TN",
        TASK_NAME,
        "/TR",
        command,
    ]
    code, out, err = run_cmd(args, timeout=60)
    return {"success": code == 0, "code": code, "stdout": out, "stderr": err, "task_name": TASK_NAME, "command": command}


def uninstall_windows_task() -> dict[str, Any]:
    code, out, err = run_cmd(["schtasks.exe", "/Delete", "/F", "/TN", TASK_NAME], timeout=60)
    return {"success": code == 0, "code": code, "stdout": out, "stderr": err, "task_name": TASK_NAME}


def _parse_schtasks_list(out: str) -> dict[str, str]:
    """把 schtasks /FO LIST /V 的 `字段: 值` 文本解析成 dict（跨中英文 locale 通用）。"""
    fields: dict[str, str] = {}
    for line in out.splitlines():
        key, sep, val = line.partition(":")
        key = key.strip()
        if sep and key and key not in fields:  # 多行同名（如"重复:"系列）只保留首个，避免被覆盖
            fields[key] = val.strip()
    return fields


def _pick(fields: dict[str, str], *names: str) -> str | None:
    norm = {k.replace(" ", ""): v for k, v in fields.items()}
    for name in names:
        val = norm.get(name.replace(" ", ""))
        if val is not None:
            return val
    return None


def windows_task_status() -> dict[str, Any]:
    code, out, err = run_cmd(["schtasks.exe", "/Query", "/TN", TASK_NAME, "/FO", "LIST", "/V"], timeout=60)
    fields = _parse_schtasks_list(out) if code == 0 else {}
    return {
        "installed": code == 0,
        "task_name": TASK_NAME,
        "status": _pick(fields, "模式", "状态", "Status"),
        "state": _pick(fields, "计划任务状态", "Scheduled Task State"),
        "next_run": _pick(fields, "下次运行时间", "Next Run Time"),
        "last_run": _pick(fields, "上次运行时间", "Last Run Time"),
        "last_result": _pick(fields, "上次结果", "Last Result"),
        "schedule": " ".join((_pick(fields, "重复", "Repeat") or "").split()) or None,
        "task_to_run": _pick(fields, "要运行的任务", "Task To Run"),
        "fields": fields,
        "code": code,
        "error": err or None,
    }
